### ISSUE TITLE
rdpwrap v1.6.2 Not working for Windows 10 Home Version - 21H1 & OS Build - 19043.1237

### ISSUE THREAD

**Issue by priyadarshanparida** [stascorp/rdpwrap#1530]
Hello, thanks for sharing the wrapper. Unfortunately the solution doesn't work for me. Details are as follows:
Edition: Windows 10 Home
Version: 21H1
OS Build: 19043.1237
This is what I see on running rdpconf (as an administrator)
Wrapper state: Installed  ver. 1.5.0.0
Service state: Running    ver. 10.0.19041.1202
Listener state: Not listening   [Not supported]
Any suggestion?

**Comment by clever-tech** [comment]
Hi, All! @priyanparida, thank you opened this issue!
my case is completely similar, except for:
Edition: Windows 10 Home Single language 
Version: **20H2**
OS Build: 190**42**.1237

"Not listening [Not supported]" after Windows update:

September 14, 2021—[KB5005565](https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44) (OS Builds 19041.1237, 19042.1237, and 19043.1237)

this is a common problem after updating Terminal Services (termsrv.dll) version with windows update,
it's fixed by updating the [file rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) to latest version e.g. [RDP Wrapper & Autoupdate](https://github.com/asmtron/rdpwrap#rdp-wrapper--autoupdate) project

after updating the auto update version my file  rdpwrap.ini - was found and updated successfully, I recommend this solution as the easiest

good luck!

**Comment by BALAHLOP** [comment]
After replacing the rdpwrap.ini it goes fully supported but i can't connect with second computer, it make me login off from main computer what can be the problem?
![rdpwrap](https://user-images.githubusercontent.com/79150938/133995301-e75071f1-93ed-42e5-a4e4-c31627b940bd.jpg)

**Comment by zekecarter** [comment]
> Hi, All! @priyanparida, thank you opened this issue!
> my case is completely similar, except for:
> Edition: Windows 10 Home Single language
> Version: **20H2**
> OS Build: 190**42**.1237
> 
> "Not listening [Not supported]" after Windows update:
> 
> September 14, 2021—[KB5005565](https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44) (OS Builds 19041.1237, 19042.1237, and 19043.1237)
> 
> this is a common problem after updating Terminal Services (termsrv.dll) version with windows update,
> it's fixed by updating the [file rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) to latest version e.g. [RDP Wrapper & Autoupdate](https://github.com/asmtron/rdpwrap#rdp-wrapper--autoupdate) project
> 
> after updating the auto update version my file rdpwrap.ini - was found and updated successfully, I recommend this solution as the easiest
> 
> good luck!

Try this version of rdpwrap [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7196641/rdpwrap.zip)
I happen to have the same version but it works for me.

**Comment by priyadarshanparida** [comment]
> Hi, All! @priyanparida, thank you opened this issue!
> my case is completely similar, except for:
> Edition: Windows 10 Home Single language
> Version: **20H2**
> OS Build: 190**42**.1237
> 
> "Not listening [Not supported]" after Windows update:
> 
> September 14, 2021—[KB5005565](https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44) (OS Builds 19041.1237, 19042.1237, and 19043.1237)
> 
> this is a common problem after updating Terminal Services (termsrv.dll) version with windows update,
> it's fixed by updating the [file rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) to latest version e.g. [RDP Wrapper & Autoupdate](https://github.com/asmtron/rdpwrap#rdp-wrapper--autoupdate) project
> 
> after updating the auto update version my file rdpwrap.ini - was found and updated successfully, I recommend this solution as the easiest
> 
> good luck!

Hello @clever-tech, thank you for your response. I have tried both the options i.e. autoupdate as well as manually replacing the file you gave. None worked, unfortunately. Refer attached documents for details of the steps I followed along with screenshots.

-Priyan

[RDP Wrapper Issue (Replace rdpwrap-ini file).pdf](https://github.com/stascorp/rdpwrap/files/7197000/RDP.Wrapper.Issue.Replace.rdpwrap-ini.file.pdf)
[RDP Wrapper Issue (run autoupdate project).pdf](https://github.com/stascorp/rdpwrap/files/7197001/RDP.Wrapper.Issue.run.autoupdate.project.pdf)

**Comment by priyadarshanparida** [comment]
> > Hi, All! @priyanparida, thank you opened this issue!
> > my case is completely similar, except for:
> > Edition: Windows 10 Home Single language
> > Version: **20H2**
> > OS Build: 190**42**.1237
> > "Not listening [Not supported]" after Windows update:
> > September 14, 2021—[KB5005565](https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44) (OS Builds 19041.1237, 19042.1237, and 19043.1237)
> > this is a common problem after updating Terminal Services (termsrv.dll) version with windows update,
> > it's fixed by updating the [file rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) to latest version e.g. [RDP Wrapper & Autoupdate](https://github.com/asmtron/rdpwrap#rdp-wrapper--autoupdate) project
> > after updating the auto update version my file rdpwrap.ini - was found and updated successfully, I recommend this solution as the easiest
> > good luck!
> 
> Try this version of rdpwrap [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7196641/rdpwrap.zip)
> I happen to have the same version but it works for me.


No luck! Still the same error

![image](https://user-images.githubusercontent.com/16783956/134035125-0d2c9720-1e14-4e1f-b03c-b08a1e94060c.png)

**Comment by B-CCCPcekca-HET** [comment]
Does not matter  Home or Pro, on build 19043.1237, ini file  and  autoupdater does not work :(

**Comment by philipejapa** [comment]
Hello friends, mine is working however, I can't make multiple simultaneous connections does anyone have an idea?

**Comment by B-CCCPcekca-HET** [comment]
> Hello friends, mine is working however, I can't make multiple simultaneous connections does anyone have an idea?

which file are you using, which version of the OS build you have,?

**Comment by philipejapa** [comment]
> > Olá amigos, o meu está funcionando no entanto, eu não posso fazer múltiplas conexões simultâneas alguém tem uma ideia?
> 
> qual arquivo você está usando, qual versão da compilação do SISTEMA OPERACIONAL você tem,?
![image](https://user-images.githubusercontent.com/77442690/134183083-a2cc37fb-a92b-4f1f-b69b-21420823101c.png)

**Comment by philipejapa** [comment]
![image](https://user-images.githubusercontent.com/77442690/134183378-023ce0a2-613e-4bac-9228-30a5bafa88fb.png)


AND I AM RUNNING VIA VM PERFECTLY BUT ONLY ONE CONNECTION AT A TIME

**Comment by priyadarshanparida** [comment]
> > > Olá amigos, o meu está funcionando no entanto, eu não posso fazer múltiplas conexões simultâneas alguém tem uma ideia?
> > 
> > 
> > qual arquivo você está usando, qual versão da compilação do SISTEMA OPERACIONAL você tem,?
> > ![image](https://user-images.githubusercontent.com/77442690/134183083-a2cc37fb-a92b-4f1f-b69b-21420823101c.png)

Hello @philipejapa, can you please share your rdpwrap.ini file?

**Comment by philipejapa** [comment]
> > > > Olá amigos, o meu está funcionando no entanto, eu não posso fazer múltiplas conexões simultâneas alguém tem uma ideia?
> > > 
> > > 
> > > qual arquivo você está usando, qual versão da compilação do SISTEMA OPERACIONAL você tem,?
> > > ![image](https://user-images.githubusercontent.com/77442690/134183083-a2cc37fb-a92b-4f1f-b69b-21420823101c.png)
>
[rdpwrap.TXT](https://github.com/stascorp/rdpwrap/files/7205039/rdpwrap.TXT)
 
> Hello @philipejapa, can you please share your rdpwrap.ini file?

of course i'm sent now

**Comment by sistemasemmanuel** [comment]
Please help, this is my rdp and my winver is different, the remote desktop service started it but it stops automatically, what should I do?
![rdp](https://user-images.githubusercontent.com/91153124/134228116-f228f8eb-453a-4d5c-9a9c-cf374eb53b09.png)
![winver](https://user-images.githubusercontent.com/91153124/134228120-5a4f64b0-764d-4717-ad28-fa0a4cc9aa5b.png)

>

**Comment by philipejapa** [comment]
ok, 1st download the .txt file I sent and change it to .ini extension with the same name will be rdpwrap.ini
2nd disconnect any network connection
3rd copy the rdpwrap.ini in the folder that you installed the application where the rdpconf.exe is
4th restart the computer and check if it worked

**Comment by philipejapa** [comment]
> ok, 1st download the .txt file I sent and change it to .ini extension with the same name will be rdpwrap.ini
> 2nd disconnect any network connection
> 3rd copy the rdpwrap.ini in the folder that you installed the application where the rdpconf.exe is
> 4th restart the computer and check if it worked

if it doesn't work, try to check in the advanced windows firewall if the port released in rdpconf.exe is the same as in the remote desktop inside the advanced firewall

**Comment by philipejapa** [comment]
> Please help, this is my rdp and my winver is different, the remote desktop service started it but it stops automatically, what should I do?
> ![rdp](https://user-images.githubusercontent.com/91153124/134228116-f228f8eb-453a-4d5c-9a9c-cf374eb53b09.png)
> ![winver](https://user-images.githubusercontent.com/91153124/134228120-5a4f64b0-764d-4717-ad28-fa0a4cc9aa5b.png)
> 
> >

cara se vc for brasileiro me chama no gmail philipejapa@gmail.com

**Comment by priyadarshanparida** [comment]
@philipejapa, thank you for sharing the file. That did not work for me, unfortunately. However, the good thing is that I found a solution on this thread:
https://github.com/stascorp/rdpwrap/issues/1520
The file from cahebebe along with steps suggested by flybeye did the trick! Finally!!!

![image](https://user-images.githubusercontent.com/16783956/134239982-9b13aa04-c518-4759-8e91-3021b4680ccf.png)

I am summarizing everything below, hope some of you can benefit from this!
**Note: The rdpwrap.ini seems to be tightly coupled with Windows OS version / Remote Desktop Services version. What worked for me might not work for another person. That's just the way it is, I suppose.**

This is my windows version (locate this in Settings, the fix is dependent on this to a large extent)
Edition:	Windows 10 Home
Version:	21H1
OS build:	19043.1237

**Pre-requisites**
1. You should have already installed RDP Wrapper Library v1.6.2. If not, you can find the same here:
https://github.com/stascorp/rdpwrap/releases/tag/v1.6.2
2. Turn of Windows Defender or keep third party antivirus disabled  for the duration of this change.
3. You will need admin rights.

**Steps**
1. Use this file (change the extension to .ini)
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/7205862/rdpwrap.txt)
2. Stop Remote Desktop Service, termservice, via Services.msc, or command line with admin, net stop termservice
3. Replace **rdpwrap.ini** in _%PROGRAMFILES%\RDP Wrapper_ folder with the version from Step 1.
4. Start Remote Desktop Service, termservice, via Services.msc, or command line with admin, net start termservice
5. Now you can connect to your Windows laptop remotely using the Host Name (get it from command line: hostname). You can also check the connectivity using RDPCheck.

**Finish up**
Turn on Windows Defender (or enable third party antivirus) and whitelist all the files related to RDP Wrapper typically found in %PROGRAMFILES%\RDP Wrapper and %SystemRoot%\System32

**Comment by B-CCCPcekca-HET** [comment]
I have  fully support  in all fields but  RDP not work for me.  

> > Привет друзья, мой работает, однако я не могу установить несколько одновременных подключений, есть ли у кого-нибудь идея?
> 
> какой файл вы используете, какая у вас версия сборки ОС?

[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7209224/rdpwrap.ini.txt)
 use this  file
even if all the fields are green, it still does not allow creating more than one connection

**Comment by blenky1998** [comment]
> Hi, All! @priyanparida, thank you opened this issue!
> my case is completely similar, except for:
> Edition: Windows 10 Home Single language
> Version: **20H2**
> OS Build: 190**42**.1237
> 
> "Not listening [Not supported]" after Windows update:
> 
> September 14, 2021—[KB5005565](https://support.microsoft.com/en-us/topic/september-14-2021-kb5005565-os-builds-19041-1237-19042-1237-and-19043-1237-292cf8ed-f97b-4cd8-9883-32b71e3e6b44) (OS Builds 19041.1237, 19042.1237, and 19043.1237)
> 
> this is a common problem after updating Terminal Services (termsrv.dll) version with windows update,
> it's fixed by updating the [file rdpwrap.ini](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) to latest version e.g. [RDP Wrapper & Autoupdate](https://github.com/asmtron/rdpwrap#rdp-wrapper--autoupdate) project
> 
> after updating the auto update version my file rdpwrap.ini - was found and updated successfully, I recommend this solution as the easiest
> 
> good luck!

Thanks worked a treat.  Thanks

I downloaded the ini file linked above,  Copied it over the old one as couldn't delete or rename the old one as in use.  Copy over by new one worked.  Then renamed rdpwrap_new.ini to rdpwrap_new_old.ini and copied new rd[wrap.ini to rdp_wrap_new.ini so both same contents.  

Ran the autoupdate bat file, rebooted and Viola!

**Comment by sistemasemmanuel** [comment]
good afternoon. Please I need your help, this is my rdp wrapper, it worked perfectly, I have done almost all the procedures, I think the problem persists is that the remote service when I start it automatically stops it does not start permanently, please can you help me solve ? I thank you very much.
![rdp wra](https://user-images.githubusercontent.com/91153124/134399074-54ea4683-31f4-49fa-bc49-6a83f40e5b37.png)


>

**Comment by blenky1998** [comment]
@sistemasemmanuel follow the instructions posted by @clever-tech  and my steps

You should end up with the diagnostics looking like the one below

![Capture](https://user-images.githubusercontent.com/30392543/134439155-67c8c022-6f7a-4c79-9a82-f984e1d7f9dd.JPG)

**Comment by dantizt** [comment]
![image](https://user-images.githubusercontent.com/91408843/134798976-6962e9e6-37cc-4b92-8d73-dab2cd4b60eb.png)
Windows 10 Pro
20H2
19042.867
Windows Feature Experience Pack 120.2212.551.0
Any suggestion? Please help.

**Comment by joebeem** [comment]
> I have fully support in all fields but RDP not work for me.
> 
> > > Привет друзья, мой работает, однако я не могу установить несколько одновременных подключений, есть ли у кого-нибудь идея?
> > 
> > 
> > какой файл вы используете, какая у вас версия сборки ОС?
> 
> [rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7209224/rdpwrap.ini.txt) use this file even if all the fields are green, it still does not allow creating more than one connection

This file worked for me. Thank you

**Comment by sebaxakerhtc** [comment]
same as https://github.com/stascorp/rdpwrap/issues/1509
